# -*- coding: utf-8 -*-
{
    'name': 'Smart Hospital Security & Access Control',
    'version': '1.0',
    'summary': 'Role-Based Access Control & Operations for Smart Mobile Hospital',
    'category': 'Custom',
    'license': 'LGPL-3',
    'author': 'Smart Hospital Team',
    'depends': [
        'base',
        'account',
        'hr',
        'stock',
        'purchase',
        'maintenance',
        'project',
        'calendar',
        'fleet',
        'crm',
        'point_of_sale',
        'website_hr_recruitment',
        'hr_skills',
        'hr_recruitment',
        'lunch'
    ],
    'data': [
        'security/hospital_security_groups.xml',
        'security/ir.model.access.csv',
        'security/hospital_record_rules.xml',
        'users/hospital_users.xml', 
        'users/hospital_users_groups.xml',
        'users/hospital_employees.xml',
        'fleet_logistics/inventory_locations.xml', 
        'fleet_logistics/fleet_vehicles.xml',
        'fleet_logistics/biomedical_assets.xml',
        'fleet_logistics/product_data.xml',
        'fleet_logistics/medical_products.xml',   
        'fleet_logistics/procurement_rules.xml',
        'fleet_logistics/maintenance_automation.xml',
        # 'data/automated_workflow.xml',
        'data/crm_stages.xml',
        'data/crm_data.xml',
        'data/emergency_activity.xml',
        'data/project_campaign.xml',
        'data/calendar_shift.xml',
        'data/pos_dispensary_data.xml',
        'data/skill_data.xml',          
        'data/hr_job_data.xml',
        'data/lunch_ration_data.xml',
        'views/crm_lead_view.xml',
        'views/calendar_event_views.xml',
        'views/hr_applicant_view.xml',
        'views/templates.xml',
        'views/crm_triage_views.xml'
        'views/views.xml'
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    # 'post_init_hook': 'post_init_hook',
}